version: '2'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment: 
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka-manager:
    image: kafkamanager/kafka-manager
    ports:
      - "9000:9000"
    environment: 
      ZK_HOSTS: zookeeper:2181
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
